### ISSUE TITLE
Pose for vton

### ISSUE THREAD

**Issue by JahangirButt-BU** [minar09/openpose-pytorch#1]
Trying to get pose for  https://github.com/minar09/cp-vton-plus i used demo_body.py for pose, it did generate file but when using in vton this error comes up.
Any idea on the problem?
![image](https://user-images.githubusercontent.com/72991763/98443692-c7d88480-212e-11eb-8f3d-fdbf39658713.png)
![image](https://user-images.githubusercontent.com/72991763/98443697-d030bf80-212e-11eb-9616-f1be764f490c.png)

**Comment by minar09** [comment]
Please use the original openpose from the official repository. This one is not relevant to the CP-VTON+.

**Comment by JahangirButt-BU** [comment]
can you provide the link, that you used to generate the key points (OpenPose). thankyou @minar09
